export const REQ_STANDARD_HEADERS = [ 'Accept', 'Accept-Charset', 'Accept-Encoding', 'Accept-Language', 'Accept-Datetime', 'Authorization', 'Cache-Control', 'Connection', 'Cookie', 'Content-Length', 'Content-MD5', 'Content-Type', 'Date', 'Expect', 'Forwarded', 'From', 'Host', 'If-Match', 'If-Modified-Since', 'If-None-Match', 'If-Range', 'If-Unmodified-Since', 'Max-Forwards', 'Origin', 'Pragma', 'Proxy-Authorization', 'Range', 'Referer', 'TE', 'User-Agent', 'Upgrade', 'Via', 'Warning' ];
export const REQ_NON_STANDARD_HEADERS = [ 'X-Requested-With', 'DNT', 'X-Forwarded-For', 'X-Forwarded-Host', 'X-Forwarded-Proto', 'Front-End-Https', 'X-Http-Method-Override', 'X-ATT-DeviceId', 'X-Wap-Profile', 'Proxy-Connection', 'X-UIDH', 'X-Csrf-Token' ];
export const RES_STANDARD_HEADERS = [ 'Access-Control-Allow-Origin', 'Accept-Patch', 'Accept-Ranges', 'Age', 'Allow', 'Alt-Svc', 'Cache-Control', 'Connection', 'Content-Disposition', 'Content-Encoding', 'Content-Language', 'Content-Length', 'Content-Location', 'Content-MD5', 'Content-Range', 'Content-Type', 'Date', 'ETag', 'Expires', 'Last-Modified', 'Link', 'Location', 'P3P', 'Pragma', 'Proxy-Authenticate', 'Public-Key-Pins', 'Refresh', 'Retry-After', 'Server', 'Set-Cookie', 'Status', 'Strict-Transport-Security', 'Trailer', 'Transfer-Encoding', 'TSV', 'Upgrade', 'Vary', 'Via', 'Warning', 'WWW-Authenticate', 'X-Frame-Options' ];
export const RES_NON_STANDARD_HEADERS = [ 'X-XSS-Protection', 'Content-Security-Policy', 'X-Content-Security-Policy', 'X-WebKit-CSP', 'X-Content-Type-Options', 'X-Powered-By', 'X-UA-Compatible', 'X-Content-Duration', 'Upgrade-Insecure-Requests', 'X-Request-ID', 'X-Correlation-ID' ];
export const HTTP_STATUS = [
    { status: '100', name: 'Continue' },
    { status: '101', name: 'Switching Protocols' },
    { status: '102', name: 'Processing' },
    { status: '103', name: 'Checkpoint' },
    { status: '200', name: 'OK' },
    { status: '201', name: 'Created' },
    { status: '202', name: 'Accepted' },
    { status: '203', name: 'Non-Authoritative Information' },
    { status: '204', name: 'No Content' },
    { status: '205', name: 'Reset Content' },
    { status: '206', name: 'Partial Content' },
    { status: '207', name: 'Multi-Status' },
    { status: '208', name: 'Already Reported' },
    { status: '226', name: 'IM Used' },
    { status: '300', name: 'Multiple Choices' },
    { status: '301', name: 'Moved Permanently' },
    { status: '302', name: 'Found' },
    { status: '302', name: 'Moved Temporarily' },
    { status: '303', name: 'See Other' },
    { status: '304', name: 'Not Modified' },
    { status: '305', name: 'Use Proxy' },
    { status: '307', name: 'Temporary Redirect' },
    { status: '308', name: 'Permanent Redirect' },
    { status: '400', name: 'Bad Request' },
    { status: '401', name: 'Unauthorized' },
    { status: '402', name: 'Payment Required' },
    { status: '403', name: 'Forbidden' },
    { status: '404', name: 'Not Found' },
    { status: '405', name: 'Method Not Allowed' },
    { status: '406', name: 'Not Acceptable' },
    { status: '407', name: 'Proxy Authentication Required' },
    { status: '408', name: 'Request Timeout' },
    { status: '409', name: 'Conflict' },
    { status: '410', name: 'Gone' },
    { status: '411', name: 'Length Required' },
    { status: '412', name: 'Precondition Failed' },
    { status: '413', name: 'Payload Too Large' },
    { status: '413', name: 'Request Entity Too Large' },
    { status: '414', name: 'URI Too Long' },
    { status: '414', name: 'Request-URI Too Long' },
    { status: '415', name: 'Unsupported Media Type' },
    { status: '416', name: 'Requested range not satisfiable' },
    { status: '417', name: 'Expectation Failed' },
    { status: '418', name: 'I\'m a teapot' },
    { status: '419', name: 'Insufficient Space On Resource' },
    { status: '420', name: 'Method Failure' },
    { status: '421', name: 'Destination Locked' },
    { status: '422', name: 'Unprocessable Entity' },
    { status: '423', name: 'Locked' },
    { status: '424', name: 'Failed Dependency' },
    { status: '426', name: 'Upgrade Required' },
    { status: '428', name: 'Precondition Required' },
    { status: '429', name: 'Too Many Requests' },
    { status: '431', name: 'Request Header Fields Too Large' },
    { status: '451', name: 'Unavailable For Legal Reasons' },
    { status: '500', name: 'Internal Server Error' },
    { status: '501', name: 'Not Implemented' },
    { status: '502', name: 'Bad Gateway' },
    { status: '503', name: 'Service Unavailable' },
    { status: '504', name: 'Gateway Timeout' },
    { status: '505', name: 'HTTP Version not supported' },
    { status: '506', name: 'Variant Also Negotiates' },
    { status: '507', name: 'Insufficient Storage' },
    { status: '508', name: 'Loop Detected' },
    { status: '509', name: 'Bandwidth Limit Exceeded' },
    { status: '510', name: 'Not Extended' },
    { status: '511', name: 'Network Authentication Required' }
]
